// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using BMS.Domain.Entities;
using Microsoft.EntityFrameworkCore;

namespace BMS.Persistence.ApplicationDBContext;

public partial class BMSContext : DbContext
{
    public BMSContext(DbContextOptions<BMSContext> options)
        : base(options)
    {
    }

    public virtual DbSet<UserAccount> UserAccounts { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}