// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BMS.Domain.Entities;

[Table("UserAccount", Schema = "security")]
public partial class UserAccount
{
    [Key]
    [Column("UserAccount")]
    public int UserAccountId { get; set; }

    [StringLength(100)]
    public string Firstname { get; set; }

    [StringLength(100)]
    public string Lastname { get; set; }

    [StringLength(100)]
    public string EmailAddress { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Username { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Password { get; set; }

    public short? Usertype { get; set; }

    public bool? AdminAccess { get; set; }

    public bool? BarangayAccess { get; set; }

    public bool? IsActivated { get; set; }

    public int? CreateBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreateDate { get; set; }

    public int? LastUpdateBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastUpdateDate { get; set; }
}